### PR TITLE
Add gaps option

### PR DESCRIPTION
**Pull request by GrylledCheez**
Users can add gaps around tiles so they don't have "crowded elevator" feel

Resolves https://github.com/Fmstrat/wintile/issues/47

### CODE REVIEW

**Comment by GrylledCheez** [comment]
@phavekes, the issue was an extra newline at the beginning of the function that cause git to apply the patch 2 times.  So it's good now.

**Comment by GrylledCheez** [comment]
@phavekes, can you please test the gaps feature on your end?

**Comment by GrylledCheez** [comment]
@Fmstrat, can I get you to check out the gaps? It's nighttime where @phavekes is.

**Comment by GrylledCheez** [comment]
@Fmstrat, can we please get this released?

**Review by johnnymiranda — APPROVED** [review]

**Review by phavekes — APPROVED** [review]

**Pull request merged**
