### PR TITLE
Add linter and perform corrections

### PR DESCRIPTION
**Pull request by GrylledCheez**

### CODE REVIEW

**Comment by phavekes** [comment]
Is it necessary to commit the node_modules folder? Could you add it to .gitignore?

**Comment by Fmstrat** [comment]
Hey @GrylledCheez, please roll back the commits or start a new branch pre-merge without `node_modules`. Having the commit included increases the size of the repo significantly.

This may need to be started in a fully separate branch as a patch to get rid of the history completely. Thanks!

**Comment by GrylledCheez** [comment]
@Fmstrat, did that work?

**Comment by GrylledCheez** [comment]
All js files linted
- [x] extension.js
- [x] prefs.js
- [x] keybindings.js

**Comment by GrylledCheez** [comment]
What's the concensus for adding hooks/pre-commit that will run eslint before accepting a commit?

**Comment by GrylledCheez** [comment]
@phavekes, stop force pushing.  Just do single commits.  We can squash them in a rebase later.

**Comment by phavekes** [comment]
> @phavekes, stop force pushing. Just do single commits. We can squash them in a rebase later.

Sorry fior that. Can't get eslint to work in GHA.

**Comment by GrylledCheez** [comment]
For some reason, your commit messed up the tabbing in the .eslintrc.yml for 

- 'CallExpression[callee.object.name=GObject][callee.property.name=registerClass] > ClassExpression:first-child'

**Comment by GrylledCheez** [comment]
@phavekes, I'm going to revert and force push back, and we can pretend none of this happened :D 
This branch is cursed.

**Comment by GrylledCheez** [comment]
be sure to do a `git fetch --all` to make sure you have a clean history

**Comment by GrylledCheez** [comment]
I'm going to abandon this branch for now. But we will still need to do lining before the next version. For now keep pulling to the develop branch and we can do a lint there when we're ready.

**Pull request closed without merging**
