### PR TITLE
4 rows, 5 cols, grow, and ctrl drop/resize

### PR DESCRIPTION
**Pull request by GrylledCheez**

### CODE REVIEW

**Comment by GrylledCheez** [comment]
1. Add 1-4 row option
1. Add 5 Col version
2. Add `<ctrl>`+`<Super>`+`<Arrow>` will grow in that direction of there's room
1. Reworded log messages for simplicity
1. Add ctrl+drag to drop a tile to any grid
1. change the way neighbor monitors are found
1. add row/Col option for ultrawide-only
3. fix `build.sh` to only include necessary files for EGO

**Comment by GrylledCheez** [comment]
@phavekes, what do you think?

**Comment by GrylledCheez** [comment]
@Fmstrat, I just added some cool new features.  Let me know what you think.

**Comment by GrylledCheez** [comment]
@Fmstrat, can you at least give the :eyes: to let me know you've seen it?

**Comment by GrylledCheez** [comment]
How is it broken?

**Comment by GrylledCheez** [comment]
Get some debug logs around the bad behavior. 
If you can, do a bisect and find out what went bad.

**Comment by GrylledCheez** [comment]
Are you able to drag and hold ctrl the release click?

**Comment by phavekes** [comment]
Dragging works fine, but a non-tiled window can not be sent to a tile position with keyboard only anymore. The logs show `[WinTile], sendMove) Not in tile.` at that moment

**Comment by GrylledCheez** [comment]
confirmed that this affects rows and columns of 2 on standard screens. I'll track it down

**Comment by GrylledCheez** [comment]
@phavekes, thanks for finding that. check b2dc121

**Comment by GrylledCheez** [comment]
please check off these things as they work

- [ ] keyboard moving
- [ ] mouse moving around edges
- [ ] ctrl+click and drag/drop
- [ ] click drag, then ctrl+super and drag/drop
- [ ] 1-5 rows

**Review by phavekes — APPROVED** [review]

**Pull request merged**
