### PR TITLE
Condense 3x2 and 4x2

### PR DESCRIPTION
**Pull request by GrylledCheez**
I combined the 3x2 and 4x2 switchcases since they were basically the same.  I haven't seen any troubles since I did that.  If you accept this one, I'll go ahead and combine the 2x2 as well.  This will allow us to easily extend to rows and more columns, i.e. 3x3, 4x3, etc

### CODE REVIEW

**Comment by rsxchin** [comment]
@Fmstrat, let me know what you think. I'm open to coding changes.

**Comment by phavekes** [comment]
could you rebase this to the latest develop-branch, so I can test it on gnome 44?

**Comment by rsxchin** [comment]
This is based off of the latest master branch that includes gnome 43 and 44. Am I missing something?

**Comment by phavekes** [comment]
https://github.com/Fmstrat/wintile/compare/master...develop

**Comment by rsxchin** [comment]
Can you cherrypick it to test?

**Comment by rsxchin** [comment]
@phavekes, I changed the branch I'm merging into.  Is that what you meant?  When I forked the repo, it only cloned master.

**Comment by GrylledCheez** [comment]
Closing for now

**Pull request closed without merging**
