### PR TITLE
make column count default to 2

### PR DESCRIPTION
**Pull request by Fmstrat**

### CODE REVIEW

**Comment by GrylledCheez** [comment]
Don't forget to push the compiled schema as well

**Comment by Fmstrat** [comment]
Is the schema being kept in the repo now? Vs built on demand?

**Comment by GrylledCheez** [comment]
> Is the schema being kept in the repo now? Vs built on demand?

`git log --follow --binary schemas/gschemas.compiled` shows that it was first added to the repo on 1 Jan 2020, and it's been updated every time we add a setting or change a default value.

**Comment by Fmstrat** [comment]
Oh I'm happy for it to be in, for some reason I thought it wasn't, though. Losing my mind. Thanks!

**Comment by GrylledCheez** [comment]
Still just waiting on that approval so we can merge. 

It sounds like you're okay with everything we've done and it all works for you.

**Comment by Fmstrat** [comment]
Yes, I am good. Once you've formalized the release I'll send the ZIP off to Ubuntu. Thanks again!

**Comment by GrylledCheez** [comment]
v11 is live and I uploaded the built zip file

**Comment by Fmstrat** [comment]
Still waiting on GNOME. They seem to have it stuck on a no-feedback v10. I've reached out this morning, too.

**Comment by GrylledCheez** [comment]
The weird thing is that they updated the blurb on the extensions page to v11, but the download is still v7.

**Pull request merged**
