### PR TITLE
Porting to GNOME 45

### PR DESCRIPTION
**Pull request by ff2400t**
This PR works fine on my fedora 39 with GNOME 45. It has code for both Gnome 45 and versions before with comments showing which sections work for which version. The code for the older version is commented out. This was based on this comment by @GrylledCheez in https://github.com/Fmstrat/wintile/issues/165#issuecomment-1763581358_
 
I also added settings.ui to the build package which was not included in build.sh script before.

### CODE REVIEW

**Comment by GrylledCheez** [comment]
Does the preferences window work for you as well? And I don't know how I missed adding the settings.ui

**Comment by ff2400t** [comment]
Yep, Preference windows is working for me now.

**Comment by GrylledCheez** [comment]
@ff2400t, I'm surprised you didn't have to make any alterations to the keybindings.js

I'll make some small adjustments to your code before I merge it in. But thanks for doing the G45 legwork. I've been dragging my feet until Ubuntu forces it on me in the spring.

**Comment by GrylledCheez** [comment]
@ff2400t, run eslint and fix your whitespace and quoting issues.
`npx eslint . --ext .js --ignore-pattern node_modules/ --fix` then perform another commit to your Fmstrat#179 PR

**Comment by danieldemus** [comment]
@GrylledCheez Now that the linting is ok, could you merge this and release a version that supports G45. Fedora 39 (and soon 40) have been using it for some time now.

**Pull request merged**
