### PR TITLE
updated metadata - corrected v41and added v42

### PR DESCRIPTION
**Pull request by mdfahner**
Manually installed on my system using gnome 42, tried it out, seems to work.

I'm new to wintile so it's certainly not thorough testing but core snapping to 2 or 4 columns with keyboard shortcuts appears to work properly.

### CODE REVIEW

**Comment by LorenzoMorelli** [comment]
I tried this on my pc (archlinux with gnome 41.5) where the original extension was not compatible and with this it seems work good!

**Review by JSkier21 — APPROVED** [review]
Tested in Gnome 42, ArchLinux. Configuration, and tiling works appropriately in GTK3, GTK4, and QT5/6 apps tested.

**Review by svemat01 — APPROVED** [review]
Tested in ArchLinux/EndevourOS with GNOME 42, animations are a bit bugged but the rest work as I'd expect. Haven't tried the older version of this extension tho.

**Comment by FlyingFathead** [comment]
Hi! 

Just updated to Ubuntu Desktop 22.04 LTS from the previous short-term Ubuntu version. Sadly, WinTile is listed as "not supported by the current GNOME version" in the Extensions application.

I suppose there's a way to bypass that somehow, given that people have been able to install WinTile on GNOME 42?

**Comment by svemat01** [comment]
> Hi!
> 
> Just updated to Ubuntu Desktop 22.04 LTS from the previous short-term Ubuntu version. Sadly, WinTile is listed as "not supported by the current GNOME version" in the Extensions application.
> 
> I suppose there's a way to bypass that somehow, given that people have been able to install WinTile on GNOME 42?
@FlyingFathead 

Not sure if it's the best way but it works. Go over to the normal extension page for wintile, instead of the on/off button you can see a download picker a bit further down in the box. Select the latest you can, probably shell 40 version 7. 

After downloading the zip file, open it and edit the manifest.json and add `42` to the list of shell versions supported. Then extract this zip file to a folder called `wintile@nowsci.com` at `~/.local/share/gnome-shell/extensions/`

The files should be in that folder you just made, not a folder in that folder. Now reboot your computer or log in and out and then run `gnome-extensions enable wintile@nowsci.com` and it should work. Good luck :)

**Comment by sinanonur** [comment]
I am on Ubuntu 22.04 LTS , GNOME 42.0 
I just added "42" to shell-version list in metadata.json, build and force installed it.
Seems to be working. Just updating versions might make this available.

This extension just makes GNOME usable for me :)

**Review by ellepdesk — APPROVED** [review]
Trivial change, approved

**Comment by joseph-zhong** [comment]
Tested also on my Ubuntu 22.04 / Gnome-Shell 42 and works like a charm, thanks!

**Review by BeiNacht — COMMENTED** [review]
Tested under Arch Linux and works fine

**Review by kylegordon — APPROVED** [review]

**Review by Fire-man-x — APPROVED** [review]
Tested on my Ubuntu 22.04 / Gnome-Shell 42 and works fine.

**Comment by mhalano** [comment]
@Fmstrat Do we have any strong reasons to not merge this PR? I think it would benefit us all

**Comment by michelbarnich** [comment]
I think @Fmstrat isnt actively maintaining this repo anymore, tge last commit is from months ago :/

**Comment by Kerwood** [comment]
This guy here forked the project and merges the commits. Use this instead.
https://github.com/Captn138/wintile-reloaded

**Comment by michelbarnich** [comment]
Thanks, will use this now!

**Comment by DanielGlaas** [comment]
> This guy here forked the project and merged the commits. Use this instead. https://github.com/Captn138/wintile-reloaded

According to the link in the Readme of this repo, one should be able to install the extension via this link:
https://extensions.gnome.org/extension/5170/wintile-reloaded-windows-10-window-tiling-for-gnom/

However, this not a valid url and creating of issues is not possible in this repo. So unfortunately, this does not really look like an alternative. :-(.

**Comment by Kerwood** [comment]
@DanielGlaas You will have to install it manunally. 

Download the `wintile-reloaded-8.tar.gz` file from the release page.
Extract and move.
```
tar -zxvf wintile-reloaded-8.tar.gz
mv wintile-reloaded-8 ~/.local/share/gnome-shell/extensions/wintile-reloaded@jaajeur.xyz
```
Enable it
```
gnome-extensions enable wintile-reloaded@jaajeur.xyz
```

**Comment by DanielGlaas** [comment]
@Kerwood : Thank you for your quick reply.
Taking your explanation into account, I was now able to get WinTile working ob Ubuntu 22.04.01.

Thank you!

**Review by franciscogouveia — APPROVED** [review]
Tested locally - works well, including the settings as far as I can tell.

**Comment by ElectricRCAircraftGuy** [comment]
Can anyone merge this?

**Comment by ElectricRCAircraftGuy** [comment]
For anyone following @DanielGlaas 's helpful instructions (thank you!), you need to log out of Ubuntu and then log back in before the "enabling it" step will work. You can also enable it from your browser here: https://extensions.gnome.org/local/.

Look for "WinTile RELOADED":

**Comment by ElectricRCAircraftGuy** [comment]
I just added detailed WinTile Reloaded installation instructions here: [How can I automatically resize a window to 1/4 of the screen and snap it to a corner in Ubuntu 22.04?](https://askubuntu.com/a/1446690/327339)

**Review by ElectricRCAircraftGuy — APPROVED** [review]
Approved. I also tested this in Ubuntu 22.04 with GNOME 42.5. 

See my detailed WinTile Reloaded installation instructions here: [How can I automatically resize a window to 1/4 of the screen and snap it to a corner in Ubuntu 22.04?](https://askubuntu.com/a/1446690/327339), meanwhile, until this is merged.

**Comment by phavekes** [comment]
Solved in #88

**Comment by ElectricRCAircraftGuy** [comment]
Now that WinTile reloaded is deleted (it was here: https://github.com/Captn138/wintile-reloaded), and WinTile still isn't updated in Gnome, how do we install WinTile? I'm stuck again.

**Comment by GrylledCheez** [comment]
> Now that WinTile reloaded is deleted (it was here: https://github.com/Captn138/wintile-reloaded), and WinTile still isn't updated in Gnome, how do we install WinTile? I'm stuck again.

Go to the develop branch and look at the README.md there. Let me know if you need any changes to the wording.

**Comment by ElectricRCAircraftGuy** [comment]
Here are my new instructions: https://github.com/Fmstrat/wintile/issues/128#issue-1739989355

Using the Gnome extension page doesn't work, because you set the version to only handle up to Gnome 40, but Gnome 42 and 42.5 are both out now. Ubuntu 22.04 is Gnome 42.5. 

https://extensions.gnome.org/extension/1723/wintile-windows-10-window-tiling-for-gnome/

**Pull request closed without merging**
