### PR TITLE
fix issues with mutter reverting window to previous size on wayland

### LINKED ISSUE #74: Since gnome-shell 41.3 window switch back to previous size when switching window
Fedora 35 on wayland

Let say i resize a window from 1/2 to 1/4 then if i switch to another window it will resize back to 1/2. I was looking around and saw that the gTile extension is also facing the same issue here: https://github.com/gTile/gTile/issues/267 

It might be worth to follow this thread to figure out the issue

### PR DESCRIPTION
**Pull request by lamarios**
fixes #74

### CODE REVIEW

**Comment by lamarios** [comment]
Actually, this doesn't work for GTK4 apps.

**Comment by Fmstrat** [comment]
@lamarios Can you provide a description of how to test this prior to merge?

**Comment by rsxchin** [comment]
@Fmstrat, how to reproduce bad behavior.
1. open an application
2. snap it to any predefined wintile area
3. try to resize from any corner/edge
4. watch the window jump oddly

Expected behavior is that height or width be maintained depending on if x or y is changing.

**Comment by phavekes** [comment]
I think I have reproduced your issue. Can you confirm this is what you are describing?
[Screencast from 2023-04-25 10-59-27.webm](https://user-images.githubusercontent.com/3096423/234227678-d791943d-3c83-42f4-8e3a-0fefb52e395b.webm)

**Comment by rsxchin** [comment]
That's the issue perfectly

**Comment by rsxchin** [comment]
@lamarios, can you resolve this conflict yourself? I'd rather not push to your master branch.

**Comment by lamarios** [comment]
let me see, I haven't used this extension in a long time :)

**Comment by lamarios** [comment]
Ok, done, not sure if this is still a necessary work around as the linked issue has been closed

**Comment by GrylledCheez** [comment]
Please grab the latest version v10 and let us know

**Comment by lamarios** [comment]
Looks like it's working as expected without my PR on gnome 44. My still be necessary for older versions, I'll close first.

**Pull request closed without merging**
