### PR TITLE
Merge Develop into master for v11

### PR DESCRIPTION
**Pull request by GrylledCheez**
There are a lot of scary looking changes, but that's mostly due to swapping tabs for spaces and adding commas to the end of lists per the style guide.

Some notable changes include
1. updating the gitignore to exclude node_modules/ for the future
2. fixed animation stutter
3. added a zone on the bottom that will spawn at full width on the bottom row
4. build.sh starts clean before building and we made the arguments easier to read
5. fixed the pixels on the right of screens by tacking them onto the end of the last column
6. updated the README.md and metadata.json
7. incremented the version to 11
8. ADDED AUTOMATIC LINTER FOR PUSHES AND PULLS TO DEVELOP OR MASTER
9. linted all 3 js files with the gjs style guide.
- swapped tabs for spaces
- added jsdoc explanations for each function
- removed dead functions that have no callers
- changed all snake case to camel case (just_some_variable vs justSomeVariable) 
- made all comparisons === instead of == because that's what they want for some reason
- swapped all concatenated log strings with interpolated strings

@Fmstrat, please let us know what you think and if there are any changes you need.

### CODE REVIEW

**Comment by GrylledCheez** [comment]
I just want to ask that this gets squashed on merge.

**Comment by GrylledCheez** [comment]
@phavekes, are you comfortable with these changes?

**Comment by GrylledCheez** [comment]
@Fmstrat, please, please, please accept this PR....

**Review by GrylledCheez — COMMENTED** [review]
Still good to me

**Comment by GrylledCheez** [comment]
@ba32107 and @phavekes, I just need 1 of you to approve. If neither of you want of be maintainers anymore, please tell @Fmstrat

**Comment by GrylledCheez** [comment]
@phavekes, I didn't mean for that to sound as threatening as it was.

**Comment by phavekes** [comment]
@GrylledCheez Why did you delete develop?

**Comment by GrylledCheez** [comment]
Merely to recreate it and sync it with master. (But really, because master had 1 commit ahead of it)

**Comment by GrylledCheez** [comment]
Would you kindly make a v11 tag and submit a properly worded release?

**Comment by ba32107** [comment]
I do not have time to maintain this project anymore, @Fmstrat feel free to remove me

**Pull request merged**
