### PR TITLE
add portrait mode

### LINKED ISSUE #160: Portrait mode displays not supported
My 4k in portrait mode does not appear to be properly supported.
I cannot, for example, get the target coloring to appear anywhere on the bottom.

My display configuration is:

- Primary: 3840x1600 to the left
- Secondary (extended): 3840x2160 @ 150% to the right in portrait

I am expecting my primary to be detected as an ultra-wide and my 4k to be detected as a non-ultra-wide.

My configuration is as follows:

- Number of columns: 3
- Number of rows: 2
- Use different rows and columsn for non-ultrawide monitors: enabled
- Number of columns for non-ultrawide: 2 (I cannot set 1 for some reason -- upon exiting it doesn't save)
- Number of rows for non-ultrawide: 2

### PR DESCRIPTION
**Pull request by GrylledCheez**
Screens in Portrait mode will automatically switch column and row values.
    Example:
    You have 2 ultrawide monitors, one is landscape, the other is portrait.
    Your config is set to 5 columns and 2 rows.
    The landscape screen with have 5 columns and 2 rows.
    The portrait screen with have 5 rows and 2 columns.
    
Resolves #160

added 1 col mode and 5 row mode by request

Perform these tests in both landscape and portrait
- [x] keyboard moving
- [x] mouse moving around edges
- [x] ctrl+click and drag/drop
- [x] click drag, then ctrl+super and drag/drop
- [x] crtl+super arrow to grow in that direction 
- [x] 1-5 rows
- [x] 1-5 columns

### CODE REVIEW

**Comment by GrylledCheez** [comment]
@skewty, try these out and let me know if they work for you.

**Comment by GrylledCheez** [comment]
@phavekes, are you good to test?

**Comment by phavekes** [comment]
Holidays, so I won't be able to test this soon

**Comment by GrylledCheez** [comment]
@Fmstrat, it's all up to you!

**Comment by GrylledCheez** [comment]
@phavekes, does it work for you?

**Comment by phavekes** [comment]
I'm not able to test this soon

**Comment by GrylledCheez** [comment]
@Fmstrat?

**Comment by phavekes** [comment]
Tested landscape view, ans everything is still working as expected. Will test portrait when I'm near a rotatable screen soon

**Review by phavekes — APPROVED** [review]

**Pull request merged**
