### PR TITLE
merge version 16 into master

### PR DESCRIPTION
**Pull request by GrylledCheez**
This version fixes the smaller hotzones and adds portrait functionality as well as some other bug fixes that arose when I did too many pull requests that caused conflicts.

I also shifted to adw and rearranged the settings widget to get ready for the Gnome 45 transition.

### CODE REVIEW

**Comment by GrylledCheez** [comment]
@Fmstrat, what do you think about the new preferences layout?

**Comment by GrylledCheez** [comment]
@phavekes, are you still active?

**Comment by phavekes** [comment]
> @phavekes, are you still active? 

I'll test this version soon

**Comment by phavekes** [comment]
I've updated to Gnome 45, so I won't be able to test for version 44 anymore

**Comment by GrylledCheez** [comment]
I'll finish my g45 strain then and get you to try that instead.

**Comment by GrylledCheez** [comment]
@phavekes, do you still have access to your older build and could test and approve approve it anyway? I'd like your help with the g45 transition of you are able to code.

**Comment by GrylledCheez** [comment]
@Fmstrat, and I know that you still have approval authority

**Review by phavekes — APPROVED** [review]

**Pull request merged**
