### PR TITLE
Support shell version 42 and 43

### PR DESCRIPTION
**Pull request by phavekes**
Also remove extra quote in 41, and update package version. Tested on Ubuntu 22.10, Gnome-shell 43.0

### CODE REVIEW

**Review by charlesritchea — APPROVED** [review]

**Review by SalahHW — APPROVED** [review]

**Review by FranP-code — APPROVED** [review]

**Review by JanusDC — APPROVED** [review]

**Comment by JanusDC** [comment]
I confirm it works perfectly on Gnome Shell 43.

**Review by arteeh — APPROVED** [review]

**Comment by mrcrilly** [comment]
Working great on `42.5` on Ubuntu 22.04.

**Review by rsxchin — APPROVED** [review]
These changes work on my Ubuntu environment as well. Please approve

**Comment by phavekes** [comment]
@Fmstrat Could you take a look at this?

**Comment by SteamWind** [comment]
Seems that we can approve by ourself. Does someone who tested it can approve it?

**Comment by Fmstrat** [comment]
Sorry folks, I thought I had assigned an approver here. Would someone like to volunteer to be promoted? ;)

**Comment by Fmstrat** [comment]
Since this is a basic change, I'll approve now. @phavekes would you be interested in helping take on administration of PRs?

**Review by Fmstrat — APPROVED** [review]

**Comment by phavekes** [comment]
Let me know if I can help with anything

**Comment by Fmstrat** [comment]
@phavekes I've sent you an invite to be a collaborator on the repo. If you have any desire to investigate/test/approve any of the existing PRs, I (and users) would highly appreciate it. I've been meaning to get to them so I can push another release out. Thanks in advance!

**Comment by phavekes** [comment]
@Fmstrat could you release this to the gnome extentions store?

**Comment by rsxchin** [comment]
@Fmstrat, I'd be interested in doing testing and approvals when I have spare cycles

**Pull request merged**
