### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by GrylledCheez**
Includes most of the common errors that cause eslint to fail.

### CODE REVIEW

**Comment by GrylledCheez** [comment]
@phavekes, thoughts?

**Comment by phavekes** [comment]
I would prefer to move the linting stuff to a github action, instead of manual instructions.

**Comment by GrylledCheez** [comment]
With the pre-commit hook, my code won't even save if the --fox can't fix it automatically. There's no need to wait for the push to know it'll fail.

Either way, those are worded as "highly suggested".

Before you bring it up, almost all of my lint fails are from merge conflicts.  :D

**Comment by GrylledCheez** [comment]
Now that I think about it, I'm not sure if you can see the actions. I get nasty emails when a run fails. 
https://github.com/Fmstrat/wintile/actions

**Review by phavekes — APPROVED** [review]

**Pull request merged**
