### PR TITLE
Merge develop to master

### PR DESCRIPTION
**Pull request by GrylledCheez**
This is the initial Gnome-45 release

### CODE REVIEW

**Comment by joser93** [comment]
After a few minutes of testing, I can say that the PR works as intended, I've waiting for an update since I'm testing on Fedora 39, so I couldn't wait to see the approval.

Tested on GNOME Shell 45.3 on Wayland

There are some weird cases that during the rendering  the resize of the window, glitches with the animation, not that anoying, but everything works as intended.

If you want to check the glitch and if it's something that you can fix, this is the step by step:
1. Open any application
2. Maximize the window if is not full maximize
3. Press <Super> + <Right Arrow>
4. Check the animation glitch on the left

I hope it helps and thanks for the effort, if there's any log or testing that I can provide to improve the extension, I'll be in touch. :D

**Comment by joser93** [comment]
I noticed that edge window resize is not working, when I posted before, I thought that wasn't implemented, but checking https://github.com/Fmstrat/wintile/pull/103 make me doubt about that, then I don't know, if is a bug or is it working as intended. 

Steps to reproduce:
1. Open two resizable apps
2. Move the window on the left and right side using `<Super> + <Left arrow>` and `<Super> + <Right arrow>`
3. Drag any window from the edge between the windows

Current behavior:
Only one window resizes

Expected behavior:
The windows resizes

**Comment by GrylledCheez** [comment]
1. What program are you trying to resize that causes the "animation glitch"?
2. What kind of animation glitch is it? Please be descriptive. 
1. Only one window resizing at a time is the intended behavior. We might implement clustering later, but that's hard.

**Comment by joser93** [comment]
> 1. What program are you trying to resize that causes the "animation glitch"?
> 2. What kind of animation glitch is it? Please be descriptive.
> 3. Only one window resizing at a time is the intended behavior. We might implement clustering later, but that's hard.

thanks for the reply

1 and 2, I add this video to showcase the rendering bug, if it's a mutter thing, then is a non issue and in the future won't ask again if someone sees that, but, if it's an issue for wintile, might help.

[Grabación de pantalla desde 2024-02-09 17-45-52.webm](https://github.com/Fmstrat/wintile/assets/6912089/938d8a76-c52d-4832-8254-5fbf9c821045)

3. I get it and thanks for being clear on that, still missed a good way to handle windows using wintile and I appreciate the effort on that :D

**Comment by GrylledCheez** [comment]
I think that's caused by us using the same ease out quad method for every animation. Put in a PR if you have any ideas.

**Comment by GrylledCheez** [comment]
@joser93, I can confirm that I'm not seeing the same glitch on my system. It must be a mutter issue like you said.

**Comment by GrylledCheez** [comment]
@Fmstrat and @phavekes, wake up.

**Comment by phavekes** [comment]
> @Fmstrat and @phavekes, wake up.

Sorry, I'm not using this plugin anymore. I'm not the right person to test this.

**Comment by rolfmadsen** [comment]
I just installed the development branch on Ubuntu 23.10 and it works beautifully! :-)

**Comment by GrylledCheez** [comment]
just curious. did you use the release or the git clone?

**Review by phavekes — APPROVED** [review]
Tested by others. Code changes look fine. 
Thanks for your work @GrylledCheez

**Pull request merged**
